"use client";
import { useEffect, useState } from "react";
type UploadedRecord={id:number;name:string;date:string;size:string;status:"ready"};
const prettySize=(bytes:number)=>bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
const prettyDate=()=>new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date());
export default function RecordUpload({onUploaded}:{onUploaded:(record:UploadedRecord)=>void}){
 const[open,setOpen]=useState(false),[file,setFile]=useState<File|null>(null),[dragging,setDragging]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const openDialog=()=>setOpen(true);window.addEventListener("carebridge:open-upload",openDialog);return()=>window.removeEventListener("carebridge:open-upload",openDialog)},[]);
 const choose=(next:File|undefined)=>{if(!next)return;if(!["application/pdf","image/jpeg","image/png"].includes(next.type)){setError("Please choose a PDF, JPG or PNG file.");return false}if(next.size>10*1024*1024){setError("That file is larger than 10 MB.");return false}setError("");setFile(next);return true};
 const close=()=>{if(busy)return;setOpen(false);setFile(null);setError("")};
 const submit=()=>{if(!file){setError("Choose a medical record first.");return}setBusy(true);window.setTimeout(()=>{onUploaded({id:Date.now(),name:file.name,date:prettyDate(),size:prettySize(file.size),status:"ready"});setBusy(false);close()},450)};
 return <><input id="record-file" className="record-file-trigger" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={e=>{if(choose(e.target.files?.[0]))setOpen(true)}}/><button className="primary hero-action" onClick={()=>setOpen(true)}>+ Add a record</button>{open&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&close()}><section className="upload-modal" role="dialog" aria-modal="true" aria-labelledby="upload-title"><div className="modal-top"><div><p className="eyebrow">MEDICAL RECORDS</p><h2 id="upload-title">Add a record</h2><p>Upload a report, prescription, discharge summary or other care document.</p></div><button className="close-btn" onClick={close} aria-label="Close">×</button></div><div className={`drop-zone ${dragging?"dragging":""} ${file?"has-file":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);choose(e.dataTransfer.files[0])}}><input id="record-file-modal" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={e=>choose(e.target.files?.[0])}/><label htmlFor="record-file-modal">{file?<><span className="upload-symbol">✓</span><strong>{file.name}</strong><small>{file.type==="application/pdf"?"PDF":file.type.includes("png")?"PNG":"JPG"} · {prettySize(file.size)} · Ready to upload</small><em>Choose another file</em></>:<><span className="upload-symbol">↑</span><strong>Drop your record here</strong><small>or click to browse from your device</small><em>PDF, JPG or PNG · up to 10 MB</em></>}</label></div>{error&&<div className="upload-error">{error}</div>}<div className="privacy-note"><span>⌁</span><div><strong>Patient-controlled</strong><small>This phase keeps the upload in the current browser session. Nothing is shared automatically.</small></div></div><div className="modal-actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary upload-submit" disabled={busy} onClick={submit}>{busy?"Adding record…":"Add record →"}</button></div></section></div>}</>;
}
